---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install nodejs"
  become: true
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Install NPM-distributed command-line tools"
  become: true
  npm:
    name: "{{ item }}"
    state: latest

- name: "Install node pm2"
  become: true
  npm:
    global: yes
    name: pm2
