- name: "extract the zipped artifact"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "start the app"
  become: true
  shell: |
    cd /home/ubuntu/backend/dist
    npm install
    pm2 stop default
    pm2 start npm -- start

