- name: "extract the zipped artifact"
  unarchive:
    src: artifact.tar.gz
    dist: /home/ubuntu/
- name: "start the app"
  shell: |
    cd /home/ubuntu/backend/dist
    npm install
    pm2 stop default
    pm2 start npm -- start

