- name: Creates directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0775
- name: "extract the zipped artifact"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "start the app"
  become: true
  shell: |
    cd /home/ubuntu/backend
    echo NODE_ENV=development > ".env"
    echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION > ".env"
    echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR > ".env"
    echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES > ".env"
    echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS  > ".env"
    echo TYPEORM_HOST=$TYPEORM_HOST  > ".env"
    echo TYPEORM_PORT=$TYPEORM_PORT  > ".env"
    echo TYPEORM_USERNAME=$TYPEORM_USERNAME  > ".env"
    echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD  > ".env"
    echo TYPEORM_DATABASE=$TYPEORM_DATABASE  > ".env"

    cd /home/ubuntu/backend/dist
    npm install
    pm2 stop default
    pm2 start npm -- start

